version: '3'

services:
  server:
    user: 10001:10001
    build: 
      context: .
    volumes:
      - instance-data:/app/instance
    ports:
      - 8000:8000
    env_file:
      - .env
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./ssl/localhost:/etc/nginx/certs:ro  # Share SSL certificates from local
      - ./ssl:/etc/nginx/certs:ro  # Share SSL certificates from local
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - instance-data:/app/instance # Share file structure
    depends_on:
      - server
    env_file: 
      - .env

volumes:
  instance-data: